<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>html2text-mcp</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="11.0.0-preview.1.26104.118" />
    <PackageReference Include="ModelContextProtocol" Version="0.8.0-preview.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Html2Text\Html2Text.csproj" />
  </ItemGroup>

</Project>
