name: Benchmark

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Run benchmarks
        run: dotnet run -c Release --project Html2Text.PerfTests

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'benchmarkdotnet'
          output-file-path: BenchmarkDotNet.Artifacts/results/Html2Text.PerfTests.PageBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
