name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  # read repo contents
  contents: read
  # write pr checks for test results
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets', '**/packages.lock.json', 'global.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Upload build outputs (bin/obj)
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          if-no-files-found: error
          retention-days: 1
          path: |
            **/bin/**
            **/obj/**

  unit-tests:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Download build outputs
        uses: actions/download-artifact@v4
        with:
          name: build-outputs
          path: .

      - name: Unit tests
        run: dotnet test ./Html2Text.Tests/Html2Text.Tests.csproj --configuration Release --no-build --no-restore --logger trx --results-directory ./UnitTestResults

      - name: Unit test report
        if: always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        uses: bibipkins/dotnet-test-reporter@v1.6.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-path: UnitTestResults/*.trx

  regression-tests:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Download build outputs
        uses: actions/download-artifact@v4
        with:
          name: build-outputs
          path: .

      - name: Regression tests
        run: dotnet test ./Html2Text.RegressionTests/Html2Text.RegressionTests.csproj --configuration Release --no-build --no-restore --logger trx --results-directory ./RegressionTestResults

      - name: Regression test report
        if: always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        uses: bibipkins/dotnet-test-reporter@v1.6.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-path: RegressionTestResults/*.trx
